### ISSUE TITLE
can't tell if error or improper usage (on my part)

### ISSUE THREAD

**Issue by Delta-Ark** [life-exe/UnrealOpenAIPlugin#13]
![unnamed](https://github.com/life-exe/UnrealOpenAIPlugin/assets/9020422/b14caa3f-fac5-4eb6-959a-009997282029)

in the vision example I tried to change the model to gpto but it's still in vision preview

I'm getting rate limited and trying to fix that by switching

**Comment by Delta-Ark** [comment]
ChatGPT->SetModel(UOpenAIFuncLib::OpenAIMainModelToString(Model));

It seems like in chatGPTWorld, this is where the model gets set? I'm not sure where/how to set that in the blueprints? And/or if I can just hardcode the model in there...

**Comment by life-exe** [comment]
Unfortunately it's not possible in Blueprints at the moment. I haven't exposed this actor to blueprints and the model setup happens on BeginPlay. Try to add this over the weekend. But binaries will be available much later due to marketplace verification.
