### ISSUE TITLE
There is no input for instructions when using the assistant type 

### ISSUE THREAD

**Issue by ella0333** [life-exe/UnrealOpenAIPlugin#17]
I want to use an assistant, i see there is a node to switch the role type to assistant but there is additional features in the api for using assistants that aren't included in the nodes (that I can see), like the instructions 

https://platform.openai.com/docs/api-reference/assistants/createAssistant 

if you could add this, that would be great, thank you!

**Comment by life-exe** [comment]
Coming later this year!
