### ISSUE TITLE
Can we add an API_URL attribute to the OpenAIAuth structure(BP/CPP)?

### ISSUE THREAD

**Issue by hanckjt** [life-exe/UnrealOpenAIPlugin#2]
Because I have some LLM servers that are compatible with OpenAI's API, so I want to change it to the URL of my own server here.
Thanks!

**Comment by life-exe** [comment]
Hi, I added API interface for C++ [https://github.com/life-exe/UnrealOpenAIPlugin/blob/master/Source/OpenAI/Public/API/API.h](https://github.com/life-exe/UnrealOpenAIPlugin/blob/master/Source/OpenAI/Public/API/API.h)
Example of usage: [https://github.com/life-exe/UnrealOpenAIPlugin/blob/878d7822d95be1b99fbdfb4d88c6baee3473c5a9/Source/OpenAI/Private/Sample/APIOverview.cpp#L478](https://github.com/life-exe/UnrealOpenAIPlugin/blob/878d7822d95be1b99fbdfb4d88c6baee3473c5a9/Source/OpenAI/Private/Sample/APIOverview.cpp#L478)

For blueprints it will be more complected. Need to think how to do it better.

**Comment by hanckjt** [comment]
OK，Thanks.
I'm looking forward to it in BluePrint.

**Comment by life-exe** [comment]
Hi!

I've added URLOverride parameter to all blupeprint nodes. You can specify your own endpoint or leave it empty).
[Release is here.](https://github.com/life-exe/UnrealOpenAIPlugin/releases/tag/1.2.0-marketplace) Marketplace update will come later.

![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/68817802/b7a2687a-f63c-4626-ae2e-29e8a01f5a37)
