### ISSUE TITLE
Transcriptions from sound assets that are in memory rather than disk

### ISSUE THREAD

**Issue by gabrielbastien** [life-exe/UnrealOpenAIPlugin#4]
Would it be possible to create transcriptions from sound assets that are in memory rather than stored on disk?  Right now the blueprint only accepts a String as the "file" property.  This requires all sound assets to be saved to disk before they can be transcribed.

![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/29382881/d17abb82-b616-4cf4-a841-c87859e7789f)

**Comment by life-exe** [comment]
I don't have time to do this right now. If you have experience, you can try to do it yourself and add it as a pull request. I will merge it.
