### ISSUE TITLE
Create Chat Completion - Payload Response Struct is always empty 

### ISSUE THREAD

**Issue by js-zeitraum** [life-exe/UnrealOpenAIPlugin#5]
![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/142003828/b09458b5-bef8-4be0-aba0-634e841dd37d)

Hello, this is not fixed in any 5.2 releases so far?
https://github.com/life-exe/UnrealOpenAIPlugin/issues/3#issuecomment-1769274254

We can not update to 5.3 during production. Any way to get this fix in 5.2?

**Comment by life-exe** [comment]
Sorry, don't have time to support all versions. It fixed in 5.3
