### ISSUE TITLE
FChatCompletion converts all FStrings to lower case.

### ISSUE THREAD

**Issue by navys04** [life-exe/UnrealOpenAIPlugin#7]
While requesting all FChatCompletion FString lines converts to lower case. I tuned gpt-3.5 and when i sending request with my new fine-tuned model ID i have error what my model id is undefined.

Solution for me was to change some lines in source code of plugin. In OpenAiProvider.cpp i added new line, before setting HttpRequestPayload. 

    RequestBodyStr = RequestBodyStr.Replace(*ChatCompletion.Model.ToLower(), *ChatCompletion.Model);
    HttpRequest->SetContentAsString(RequestBodyStr);
    return HttpRequest;

**Comment by life-exe** [comment]
Fixed: https://github.com/life-exe/UnrealOpenAIPlugin/commit/2726075cf9ea93d9923842a918a2f94e146cc170
Will be in marketplace soon.
