### ISSUE TITLE
Issue with finetuned models

### ISSUE THREAD

**Issue by alegroSandermann** [life-exe/UnrealOpenAIPlugin#8]
I have some fine tuned models. I use blueprint nodes of the plugin. The "List models" node also lists this ft models. But if I use them the "Create Chat Completion" does not work. With the openAI default models everything works like expected but not with the fine tuned models. The Create Chat Completion is immediately finished and does not respond any text.
I am using ue 5.3 and the marketplace version of the plugin.

**Comment by life-exe** [comment]
Fixed: https://github.com/life-exe/UnrealOpenAIPlugin/commit/2726075cf9ea93d9923842a918a2f94e146cc170
Will be in marketplace soon.
