### ISSUE TITLE
Tools/Functions doesn't work

### ISSUE THREAD

**Issue by alegroSandermann** [life-exe/UnrealOpenAIPlugin#9]
I implement functions (BP node, UE 5.3) through tools. I defined the function and in tool choise i set to "auto".

Doesnt matter what i prompt. The response is always empty as far as Tools array is connected. I also tried Tool Choise set to "none". I think using Tools breaks the Chat Completion node.

**Comment by life-exe** [comment]
There is one undocumented thing in the function call for BP that I forgot to mention.

You need to wrap function parameters with `START_FUNCTION_OBJECT_MARKER .. END_FUNCTION_OBJECT_MARKER`

![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/68817802/a822e8be-77ee-4618-9676-c5bce11a28ad)

```
Get the current weather at a specific location

START_FUNCTION_OBJECT_MARKER{"type": "object","properties":{"location":{"type": "string","description": "The city and state, e.g. SanFrancisco, CA; Convert city name to English if necessary; don't use spaces in the parameter"},"unit":{"type": "string","enum": ["celsius","fahrenheit"]}},"required": ["location","unit"]}END_FUNCTION_OBJECT_MARKER

get_current_weather
```

Then it is going to be quite a blueprint hell:

![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/68817802/d7f72853-1eb7-45b3-b439-5ddb54fbc8f7)

But you can get the function name and args and then make an http request, for example:

![image](https://github.com/life-exe/UnrealOpenAIPlugin/assets/68817802/8d215f96-1211-407b-8f39-f3606444941d)

You can check [service examples](https://github.com/life-exe/UnrealOpenAIPlugin/tree/master/Source/OpenAI/Private/ChatGPT/Services) in the plugin sources. The functional concept requires some intensive work with JSON. So it will be a bit painful to set up BP.
